name: "Infra-Pipeline"
on: workflow_dispatch
  # push:
  #   branches:
  #     - 'main'
  #     - 'feature'
jobs:
  terraformjob:
    name: terraform job
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
      
