    name: Azure Terraform CI/CD

    on: workflow_dispatch
      # push:
      #   branches:
      #     - main # Trigger on push to main branch
    permissions:
      id-token: write
      contents: read
    
    jobs:
      terraform:
        runs-on: self-hosted
        steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Setup Terraform
            uses: hashicorp/setup-terraform@v4
          - name: Azure login
            uses: azure/login@v2
            with:
              client-id: ${{ secrets.AZURE_AD_CLIENT_ID }}
              tenant-id: ${{ secrets.AZURE_AD_TENANT_ID }}
              subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
              
          - name: Terraform Init
            run: terraform init 
            working-directory: .
            env:
              ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
              ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
              ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
              ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

          - name: Terraform Plan
            run: terraform plan
            working-directory: .
            env:
              ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
              ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
              ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
              ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

          # - name: Terraform Apply
          #   working-directory: .
          #   run: terraform apply -auto-approve
          #   env:
          #     ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
          #     ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
          #     ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
          #     ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
