name: Azure Terraform CI/CD

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
  
permissions:
  id-token: write
  contents: read

jobs:
  terraform-init-plan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # ✅ Login to Azure using Service Principal
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_AD_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_AD_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_AD_SUBSCRIPTION_ID }}
          client-secret: ${{ secrets.AZURE_AD_CLIENT_SECRET }}

      # ✅ Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5  # or whichever version you prefer

      # ✅ Terraform Init
      - name: Terraform Init
        run: terraform init
        # working-directory: ./
        working-directory: environment/dev

      # ✅ Terraform Plan
      - name: Terraform Plan
        run: terraform plan
         # working-directory: ./
        working-directory: environment/dev
        # env:
        #   ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
        #   ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
        #   ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
        #   ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_AD_SUBSCRIPTION_ID }}

      # # ✅ Terraform Apply
      # - name: Terraform Apply
      #   run: terraform apply -auto-approve
      #   # working-directory: ./
      #   working-directory: environment/dev
      #   # env:
      #   #   ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      #   #   ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      #   #   ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
      #   #   ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_AD_SUBSCRIPTION_ID }}

  terraform-apply:    
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: terraform-init-plan
    environment: dev
    steps:
     - name: Checkout
       uses: actions/checkout@v5.0.0
    
     # - name: Azure Login
     #   uses: azure/login@v2
     #   with:
     #     client-id: ${{ secrets.AZURE_AD_CLIENT_ID }}
     #     tenant-id: ${{ secrets.AZURE_AD_TENANT_ID }}
     #     subscription-id: ${{ secrets.AZURE_AD_SUBSCRIPTION_ID }}
     #     client-secret: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
     #     auth-type: id-token
          
     - name: Terraform Init
       id: init
       run: terraform init -input=false  
       working-directory: environment/dev

     - name: Terraform Apply
       id: apply
       run: terraform apply --auto-approve
       continue-on-error: true
       working-directory: environment/dev             
