name: "first-workflow"
on:
  push:
    branches:
      - 'main'
      - 'feature'
jobs:
  terraforminit:
    name: terraform init
    runs-on: self-hosted
    steps:
      - name: dhondhu
        run: echo "dhondhu"
      
