name: "Infra-Pipeline"
on: workflow_dispatch
  # push:
  #   branches:
  #     - 'main'
  #     - 'feature'
permissions:
  id-token: write
  contents: read
jobs:
  terraform-init-plan:
    name: terraform init and plan
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0   
      - name: Azure Login
        uses: Azure/login@v2.3.0
        with:
          client-id: "007db939-c185-484a-a2e4-10ab8bb8aa26"
          # client-secret: "Ik_8Q~BB57TJW8GMMbc2ExwfaN_DUb2NuS5qRcNf"
          subscription-id: "38d52de4-2fb6-4a85-96fb-5ba22d363e4e"
          tenant-id: "8839fa1a-72d2-4f19-8736-4c73cf13d7a6"
      - name: terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true
        working-directory: ./environment/dev
       

