name: Azure Terraform CI/CD

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # ✅ Login to Azure using Service Principal
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_AD_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_AD_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_AD_SUBSCRIPTION_ID }}
          client-secret: ${{ secrets.AZURE_AD_CLIENT_SECRET }}

      # ✅ Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5  # or whichever version you prefer

      # ✅ Terraform Init
      - name: Terraform Init
        run: terraform init
        working-directory: ./

      # ✅ Terraform Plan
      - name: Terraform Plan
        run: terraform plan -out=tfplan
        working-directory: ./

      # ✅ Terraform Apply
      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        working-directory: ./
