name: "Terraform-Plan-Infra-Plan"

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - FeatureBranch1

jobs:
  terraform:
    name: "Terraform"
    runs-on: self-hosted
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Optional: Setup Terraform if not installed on self-hosted runner
      # - name: Setup Terraform
      #   uses: hashicorp/setup-terraform@v2
      #   with:
      #     terraform_version: 1.7.0
      #     cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        id: init
        env:
          TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
        run: terraform init

      - name: Terraform Plan
        id: plan
        env:
          TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
        run: terraform plan -no-color
