name: "Infra-Pipeline"
on: workflow_dispatch
  # push:
  #   branches:
  #     - 'main'
  #     - 'feature'
permissions:
  id-token: write
  contents: read
jobs:
  terraform-init-plan:
    name: terraform init and plan
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
      - name: Install Terraform
        uses: little-core-labs/install-terraform@v2.0.0
        with:
          version: 1.13.0      
      - name: Azure Login
        uses: Azure/login@v2.3.0
        with:
          client-id: "f72f924c-5aa6-4e12-936d-2890cea66164"
          # client-secret: "Ik_8Q~BB57TJW8GMMbc2ExwfaN_DUb2NuS5qRcNf"
          subscription-id: "38d52de4-2fb6-4a85-96fb-5ba22d363e4e"
          tenant-id: "8839fa1a-72d2-4f19-8736-4c73cf13d7a6"
          auth-type: IDENTITY
          enable-AzPSSession: true
      - name: Terraform Init
        id: init
        env:
          ARM_CLIENT_ID: "f72f924c-5aa6-4e12-936d-2890cea66164"
          ARM_CLIENT_SECRET: "Ik_8Q~BB57TJW8GMMbc2ExwfaN_DUb2NuS5qRcNf"
          ARM_SUBSCRIPTION_ID: "38d52de4-2fb6-4a85-96fb-5ba22d363e4e"
          ARM_TENANT_ID: "8839fa1a-72d2-4f19-8736-4c73cf13d7a6"
        run: terraform init
        working-directory: ./environment/dev 

