name: "Infra-Pipeline"
on: workflow_dispatch
  # push:
  #   branches:
  #     - 'main'
  #     - 'feature'
permissions:
  id-token: write
  contents: read
jobs:
  terraformjob:
    name: terraform job
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
      - name: Install Terraform
        uses: little-core-labs/install-terraform@v2.0.0
        with:
          version: 1.13.0      
      - name: Azure Login
        uses: Azure/login@v2.3.0
        with:
          # ClientId of the Azure Service principal created.
          client-id: 007db939-c185-484a-a2e4-10ab8bb8aa26
          # TenantId of the Azure Service principal created.
          tenant-id: 8839fa1a-72d2-4f19-8736-4c73cf13d7a6
          # Azure subscriptionId
          subscription-id: 38d52de4-2fb6-4a85-96fb-5ba22d363e4e
      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true
        working-directory: environment/dev
          
      - name: Terraform init azurerm backend
  # You may pin to the exact commit or the version.
  # uses: ahmedig/terraform-azurerm-backend@65ed9d7f67790281b78670b7811d63d96f5e22ec
        uses: ahmedig/terraform-azurerm-backend@v4
        with:
          # Azure Credentials in JSON format
          azure_credentials: 
          # State file location - resource group name
          resource_group_name: 
          # State file location - container name
          container_name: 
          # State file location - storage account name
          storage_account_name: 
          # State file location - file name
          file_name: # optional, default is terraform.tfstate
          # Subscription Id of the resource group
          subscription_id: # optional, default is empty
          # Terraform working directory
          tf_working_directory: # optional, default is .
          
